platform :ios, '12.0'

inhibit_all_warnings!
  use_frameworks!

target 'Self' do

  	pod 'Firebase'
  	pod 'Firebase/Core'
	pod 'Firebase/Analytics'
	pod 'Firebase/Firestore'
	pod 'Firebase/Auth'
	pod 'Firebase/Storage'
	pod 'SnapKit'
	pod 'lottie-ios'
	pod 'NotificationBannerSwift', :git =>
		'https://github.com/Daltron/NotificationBanner'

	pod 'SwiftLint'
	pod 'SwiftyJSON'

end